version: '3.7'
services:
  jupyterlab:
    build: 
      context: ../
      dockerfile: Dockerfile.jupyterLAB
    expose:
      - 8888
    command: ["bash", "-c", "start.sh jupyter lab --ServerApp.token=${JLAB_TOKEN}"]
    env_file:
      - .env
    environment:
      - MLFLOW_S3_ENDPOINT_URL="http://minio:9000"
      - NATS_HOST="nats"
  minio:
    image: quay.io/minio/minio:RELEASE.2023-11-15T20-43-25Z
    command: ["server", "--console-address", ":40093", "/data"]
    expose:
      - 40093:40093
      - 9000:9000
    env_file:
      - .env
    volumes:
      - ./data:/data

  mlflow:
    build:
      context: ../
      dockerfile: Dockerfile.mlflow
    command: [ "/bin/bash", "-c","mlflow server --host 0.0.0.0 --serve-artifacts --artifacts-destination s3://mlflow --backend-store-uri /data/mlflow"]
    volumes:
      - ./mlflow_exp:/data/mlflow
    env_file: .env
    environment:
      - MLFLOW_S3_ENDPOINT_URL="http://minio:9000"

  nats:
    image: "docker.io/nats:2.10.5-alpine3.18"
    ports:
      - :4222/tcp
      - :8222/tcp
    command: ["-c", "/etc/nats/nats-server.conf", "-m", "8222"]
    volumes:
      - ./config/nats-server.conf:/etc/nats/nats-server.conf
    
