apiVersion: v1
kind: Namespace
metadata:
  name: hub
---
# Copyright (c) 2022 dciangot
# 
# This software is released under the MIT License.
# https://opensource.org/licenses/MIT
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: daskhub
  namespace: hub
spec:
  selector:
    matchLabels:
      app: daskhub # has to match .spec.template.metadata.labels
  serviceName: "daskhub"
  replicas: 1
  minReadySeconds: 30 # by default is 0
  template:
    metadata:
      labels:
        app: daskhub
    spec:
      serviceAccountName: jupyterhub
      automountServiceAccountToken: true
      containers:
      - name: daskhub
        image: "dciangot/daskhub:v6"
        args:
        - bash
        - -c
        - "jupyterhub --port=8083 --config=/opt/jhub/jupyterhub_config.py"
        volumeMounts:
        - name: config
          mountPath: "/opt/jhub"
          readOnly: true
        - name: hub
          mountPath: "/srv/jupyterhub"
      volumes:
      - name: config
        configMap:
          name: jhub-config
      - name: hub
        persistentVolumeClaim:
          claimName: jhub-dir

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jhub-dir
  namespace: hub
spec:
  storageClassName: openebs-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1G
---
apiVersion: v1
kind: Service
metadata:
  name: hub
  namespace: hub
spec:
  selector:
    app: daskhub
  type: ClusterIP 
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083